<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.aicanal</groupId>
    <artifactId>ai-canal-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>canal-server</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-yaml</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-cluster-zookeeper</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-egress-kafka</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-egress-netty</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-egress-rabbitmq</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-egress-rocketmq</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-ingress-netty</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.aicanal</groupId>
      <artifactId>canal-storage-default</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <execution>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <shadedArtifactAttached>true</shadedArtifactAttached>
              <shadedClassifierName>all</shadedClassifierName>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"></transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>io.github.aicanal.server.CanalServerMain</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
