package io.github.aicanal.admin.server;

import io.github.aicanal.admin.api.*;
import java.sql.*;
import java.time.Instant;
import java.util.*;

public final class JdbcConfigRepository implements ConfigRepository {
  private static final String CREATE_RELEASE_TABLE =
      "CREATE TABLE IF NOT EXISTS config_release("
          + "namespace VARCHAR(255) NOT NULL, version BIGINT NOT NULL, "
          + "content_hash VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, "
          + "content CLOB NOT NULL, created_by VARCHAR(255), "
          + "created_at TIMESTAMP WITH TIME ZONE, published_by VARCHAR(255), "
          + "published_at TIMESTAMP WITH TIME ZONE, comment CLOB, "
          + "PRIMARY KEY(namespace,version), UNIQUE(namespace,content_hash))";
  private static final String CREATE_PUBLISH_HISTORY_TABLE =
      "CREATE TABLE IF NOT EXISTS config_publish_history("
          + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
          + "namespace VARCHAR(255), version BIGINT, actor VARCHAR(255), "
          + "published_at TIMESTAMP WITH TIME ZONE)";
  private static final String CREATE_AUDIT_TABLE =
      "CREATE TABLE IF NOT EXISTS config_audit_log("
          + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
          + "occurred_at TIMESTAMP WITH TIME ZONE, actor VARCHAR(255), "
          + "operation VARCHAR(64), namespace VARCHAR(255), version BIGINT, "
          + "source_ip VARCHAR(128), detail CLOB)";
  private static final String RELEASE_COLUMNS =
      "version,content_hash,status,content,created_by,created_at,"
          + "published_by,published_at,comment";
  private static final String UPSERT_RELEASE =
      "MERGE INTO config_release("
          + "namespace,version,content_hash,status,content,created_by,created_at,"
          + "published_by,published_at,comment) KEY(namespace,version) "
          + "VALUES(?,?,?,?,?,?,?,?,?,?)";

  private final String url, user, password;

  public JdbcConfigRepository(String url, String user, String password) {
    this.url = url;
    this.user = user;
    this.password = password;
    initialize();
  }

  private Connection open() throws SQLException {
    return DriverManager.getConnection(url, user, password);
  }

  private void initialize() {
    try (Connection c = open();
        Statement s = c.createStatement()) {
      s.execute(CREATE_RELEASE_TABLE);
      s.execute(CREATE_PUBLISH_HISTORY_TABLE);
      s.execute(CREATE_AUDIT_TABLE);
    } catch (SQLException e) {
      throw new IllegalStateException("Admin database initialization failed", e);
    }
  }

  public NavigableMap<Long, ConfigRelease> load(String namespace) {
    NavigableMap<Long, ConfigRelease> m = new TreeMap<>();
    try (Connection c = open();
        PreparedStatement p =
            c.prepareStatement(
                "SELECT "
                    + RELEASE_COLUMNS
                    + " FROM config_release WHERE namespace=? ORDER BY version")) {
      p.setString(1, namespace);
      try (ResultSet r = p.executeQuery()) {
        while (r.next()) {
          Timestamp ca = r.getTimestamp(6), pa = r.getTimestamp(8);
          ConfigRelease x =
              new ConfigRelease(
                  namespace,
                  r.getLong(1),
                  r.getString(2),
                  ReleaseStatus.valueOf(r.getString(3)),
                  r.getString(4),
                  r.getString(5),
                  ca == null ? null : ca.toInstant(),
                  r.getString(7),
                  pa == null ? null : pa.toInstant(),
                  r.getString(9));
          m.put(x.getVersion(), x);
        }
      }
      return m;
    } catch (SQLException e) {
      throw new IllegalStateException(e);
    }
  }

  public Set<String> namespaces() {
    Set<String> s = new LinkedHashSet<>();
    try (Connection c = open();
        Statement q = c.createStatement();
        ResultSet r = q.executeQuery("SELECT DISTINCT namespace FROM config_release")) {
      while (r.next()) s.add(r.getString(1));
      return s;
    } catch (SQLException e) {
      throw new IllegalStateException(e);
    }
  }

  public void save(ConfigRelease r) {
    try (Connection c = open();
        PreparedStatement p = c.prepareStatement(UPSERT_RELEASE)) {
      p.setString(1, r.getNamespace());
      p.setLong(2, r.getVersion());
      p.setString(3, r.getContentHash());
      p.setString(4, r.getStatus().name());
      p.setString(5, r.getContent());
      p.setString(6, r.getCreatedBy());
      p.setTimestamp(7, timestamp(r.getCreatedAt()));
      p.setString(8, r.getPublishedBy());
      p.setTimestamp(9, timestamp(r.getPublishedAt()));
      p.setString(10, r.getComment());
      p.executeUpdate();
      if (r.getStatus() == ReleaseStatus.PUBLISHED)
        try (PreparedStatement h =
            c.prepareStatement(
                "INSERT INTO config_publish_history(namespace,version,actor,published_at) VALUES(?,?,?,?)")) {
          h.setString(1, r.getNamespace());
          h.setLong(2, r.getVersion());
          h.setString(3, r.getPublishedBy());
          h.setTimestamp(4, timestamp(r.getPublishedAt()));
          h.executeUpdate();
        }
    } catch (SQLException e) {
      throw new IllegalStateException(e);
    }
  }

  public void audit(String actor, String op, String ns, long v, String ip, String detail) {
    try (Connection c = open();
        PreparedStatement p =
            c.prepareStatement(
                "INSERT INTO config_audit_log("
                    + "occurred_at,actor,operation,namespace,version,source_ip,detail) "
                    + "VALUES(?,?,?,?,?,?,?)")) {
      p.setTimestamp(1, Timestamp.from(Instant.now()));
      p.setString(2, actor);
      p.setString(3, op);
      p.setString(4, ns);
      p.setLong(5, v);
      p.setString(6, ip);
      p.setString(7, detail);
      p.executeUpdate();
    } catch (SQLException e) {
      throw new IllegalStateException(e);
    }
  }

  public List<String> auditLog() {
    List<String> out = new ArrayList<>();
    try (Connection c = open();
        Statement s = c.createStatement();
        ResultSet r =
            s.executeQuery(
                "SELECT occurred_at,actor,operation,namespace,version,source_ip,detail "
                    + "FROM config_audit_log ORDER BY id")) {
      while (r.next())
        out.add(
            r.getTimestamp(1).toInstant()
                + " actor="
                + r.getString(2)
                + " operation="
                + r.getString(3)
                + " namespace="
                + r.getString(4)
                + " version="
                + r.getLong(5)
                + " sourceIp="
                + r.getString(6)
                + " detail="
                + r.getString(7));
      return out;
    } catch (SQLException e) {
      throw new IllegalStateException(e);
    }
  }

  private static Timestamp timestamp(Instant i) {
    return i == null ? null : Timestamp.from(i);
  }
}
